version = 5.7.0
archive_dir = /etc/letsencrypt/archive/govtitiramtek.net
cert = /etc/letsencrypt/live/govtitiramtek.net/cert.pem
privkey = /etc/letsencrypt/live/govtitiramtek.net/privkey.pem
chain = /etc/letsencrypt/live/govtitiramtek.net/chain.pem
fullchain = /etc/letsencrypt/live/govtitiramtek.net/fullchain.pem
[renewalparams]
account = 4427c8c98851da569059145af231802e
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
govtitiramtek.net = /var/www/certbot
www.govtitiramtek.net = /var/www/certbot
